name: Deploy to GitHub Pages
run-name: ${{ github.actor }} is deploying to GitHub Pages
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: mkdir gitproject
      - run: cd gitproject
      - run: ls
      - run: git clone https://github.com/sandbox-projects-org/sandbox-projects-org.github.io.git
      - run: ls
      - name: Install angular-cli-ghpages
        run: |
          npm install -g @angular/cli
          npm i angular-cli-ghpages
      - name: Build/Deploy Angular project to fit GitHub Pages format
        run: ng deploy --base-href=/
          
    
